# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_For_Main(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(360, 861)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(0, 150, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lblHead = QtWidgets.QLabel(Form)
        self.lblHead.setGeometry(QtCore.QRect(70, 40, 80, 80))
        self.lblHead.setText("")
        self.lblHead.setObjectName("lblHead")
        self.bt_search = QtWidgets.QToolButton(Form)
        self.bt_search.setGeometry(QtCore.QRect(330, 150, 31, 31))
        self.bt_search.setText("")
        self.bt_search.setAutoRaise(True)
        self.bt_search.setObjectName("bt_search")
        self.lblName = QtWidgets.QLabel(Form)
        self.lblName.setGeometry(QtCore.QRect(180, 45, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lblName.setFont(font)
        self.lblName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblName.setText("")
        self.lblName.setObjectName("lblName")
        self.lblId = QtWidgets.QLabel(Form)
        self.lblId.setGeometry(QtCore.QRect(180, 85, 91, 31))
        self.lblIcon = QtWidgets.QLabel(Form)
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setGeometry(QtCore.QRect(10, 5, 31, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lblId.setFont(font)
        self.lblId.setText("")
        self.lblId.setObjectName("lblId")
        self.closeBt = QtWidgets.QToolButton(Form)
        self.closeBt.setGeometry(QtCore.QRect(330, 0, 31, 31))
        self.closeBt.setText("")
        self.closeBt.setAutoRaise(True)
        self.closeBt.setObjectName("closeBt")
        self.minBt = QtWidgets.QToolButton(Form)
        self.minBt.setGeometry(QtCore.QRect(300, 0, 31, 31))
        self.minBt.setText("")
        self.minBt.setAutoRaise(True)
        self.minBt.setObjectName("minBt")
        self.setupBt = QtWidgets.QToolButton(Form)
        self.setupBt.setGeometry(QtCore.QRect(270, 0, 31, 31))
        self.setupBt.setText("")
        self.setupBt.setAutoRaise(True)
        self.setupBt.setObjectName("setupBt")
        self.bt_adduser = QtWidgets.QToolButton(Form)
        self.bt_adduser.setGeometry(QtCore.QRect(240, 0, 31, 31))
        self.bt_adduser.setText("")
        self.bt_adduser.setAutoRaise(True)
        self.bt_adduser.setObjectName("bt_adduser")
        self.cacheBt = QtWidgets.QToolButton(Form)
        self.cacheBt.setGeometry(QtCore.QRect(210, 0, 31, 31))
        self.cacheBt.setText('')
        self.cacheBt.setAutoRaise(True)
        self.faceBt = QtWidgets.QToolButton(Form)
        self.faceBt.setGeometry(QtCore.QRect(180, 0, 31, 31))
        self.faceBt.setText('')
        self.faceBt.setAutoRaise(True)
        self.groupBt = QtWidgets.QToolButton(Form)
        self.groupBt.setGeometry(QtCore.QRect(150, 0, 31, 31))
        self.groupBt.setText('')
        self.groupBt.setAutoRaise(True)

        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 180, 361, 681))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")

        self.friendList = QtWidgets.QWidget()
        self.friendList.setObjectName("friends")

        #self.friends = QtWidgets.QListWidget(self.friendList)
        #self.friends.setGeometry(QtCore.QRect(0, 0, 361, 661))
        #self.friends.setFrameShape(QtWidgets.QFrame.NoFrame)
        #self.friends.setObjectName("friends")

        self.treeWidget = QtWidgets.QTreeWidget(self.friendList)
        self.treeWidget.setGeometry(QtCore.QRect(0, 0, 361, 661))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeWidget.headerItem().setText(0, "1")

        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/friend.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.friendList, icon1, "好友")

        self.groupList = QtWidgets.QWidget()
        self.groupList.setObjectName("groups")
        self.groups = QtWidgets.QListWidget(self.groupList)
        self.groups.setGeometry(QtCore.QRect(0, 0, 361, 661))
        self.groups.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.groups.setObjectName("groups")
        self.groups.setFocusPolicy(QtCore.Qt.NoFocus)
        self.groups.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)

        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/group.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.groupList, icon2, "群组")


        self.retranslateUi(Form)
        #QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setToolTip(_translate("Form", "搜索好友"))
        self.lineEdit.setPlaceholderText(_translate("Form", "搜索"))
        self.lblHead.setToolTip(_translate("Form", "头像"))
        self.bt_search.setToolTip(_translate("Form", " 搜索"))
        self.lblName.setToolTip(_translate("Form", "昵称"))
        self.lblId.setToolTip(_translate("Form", "账号"))
        self.closeBt.setToolTip(_translate("Form", "关闭"))
        self.minBt.setToolTip(_translate("Form", "最小化"))
        self.setupBt.setToolTip(_translate("Form", "设置"))
        self.bt_adduser.setToolTip(_translate("Form", "添加好友"))

