# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Register_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_For_Register(object):
    def setupUi(self, Dialo):
        Dialo.setObjectName("Dialo")
        Dialo.resize(540, 406)
        font = QtGui.QFont()
        font.setFamily("黑体")
        Dialo.setFont(font)
        Dialo.setSizeGripEnabled(False)
        self.editName = QtWidgets.QLineEdit(Dialo)
        self.editName.setGeometry(QtCore.QRect(50, 230, 251, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.editName.setFont(font)
        self.editName.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.editName.setPlaceholderText("请输入您的昵称")
        self.editName.setClearButtonEnabled(False)
        self.editName.setObjectName("editName")
        self.editRepPwd = QtWidgets.QLineEdit(Dialo)
        self.editRepPwd.setGeometry(QtCore.QRect(50, 310, 251, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.editRepPwd.setFont(font)
        self.editRepPwd.setPlaceholderText("请再次输入您的密码")
        self.editRepPwd.setObjectName("editRepPwd")
        self.bcakgroundPic = QtWidgets.QWidget(Dialo)
        self.bcakgroundPic.setGeometry(QtCore.QRect(0, 0, 541, 221))
        self.bcakgroundPic.setObjectName("bcakgroundPic")
        self.closeBt = QtWidgets.QToolButton(self.bcakgroundPic)
        self.closeBt.setGeometry(QtCore.QRect(510, 0, 31, 41))
        self.closeBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeBt.setText("")
        self.closeBt.setCheckable(False)
        self.closeBt.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.closeBt.setAutoRaise(True)
        self.closeBt.setObjectName("closeBt")
        self.minBt = QtWidgets.QToolButton(self.bcakgroundPic)
        self.minBt.setGeometry(QtCore.QRect(480, 0, 31, 41))
        self.minBt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minBt.setText("")
        self.minBt.setAutoRaise(True)
        self.minBt.setObjectName("minBt")
        self.editPwd = QtWidgets.QLineEdit(Dialo)
        self.editPwd.setGeometry(QtCore.QRect(50, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.editPwd.setFont(font)
        self.editPwd.setPlaceholderText("请输入您的密码")
        self.editPwd.setObjectName("editPwd")
        self.pbLogin = QtWidgets.QPushButton(Dialo)
        self.pbLogin.setGeometry(QtCore.QRect(150, 360, 251, 41))
        self.pbLogin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pbLogin.setDefault(True)
        self.pbLogin.setFlat(False)
        self.pbLogin.setObjectName("pbLogin")
        self.label = QtWidgets.QLabel(Dialo)
        self.label.setGeometry(QtCore.QRect(440, 240, 70, 70))
        self.label.setObjectName("label")
        self.default_2 = QtWidgets.QRadioButton(Dialo)
        self.default_2.setGeometry(QtCore.QRect(330, 280, 71, 19))
        self.default_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.default_2.setChecked(True)
        self.default_2.setObjectName("default_2")
        self.choosePic = QtWidgets.QRadioButton(Dialo)
        self.choosePic.setGeometry(QtCore.QRect(330, 320, 91, 19))
        self.choosePic.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.choosePic.setObjectName("choosePic")
        self.label_2 = QtWidgets.QLabel(Dialo)
        self.label_2.setGeometry(QtCore.QRect(330, 240, 91, 16))
        self.label_2.setObjectName("label_2")
        self.scanPic = QtWidgets.QPushButton(Dialo)
        self.scanPic.setGeometry(QtCore.QRect(430, 320, 93, 28))
        self.scanPic.setObjectName("scanPic")

        self.retranslateUi(Dialo)
        QtCore.QMetaObject.connectSlotsByName(Dialo)

    def retranslateUi(self, Dialo):
        _translate = QtCore.QCoreApplication.translate
        Dialo.setWindowTitle(_translate("Dialo", "Dialog"))
        self.editName.setToolTip(_translate("Dialo", "请输入用户账号"))
        self.editRepPwd.setToolTip(_translate("Dialo", "请输入用户密码"))
        self.closeBt.setToolTip(_translate("Dialo", "关闭"))
        self.minBt.setToolTip(_translate("Dialo", "最小化"))
        self.editPwd.setToolTip(_translate("Dialo", "请输入用户密码"))
        self.pbLogin.setText(_translate("Dialo", "立即注册"))
        #self.label.setText(_translate("Dialo", "TextLabel"))
        self.default_2.setText(_translate("Dialo", "默认"))
        self.choosePic.setText(_translate("Dialo", "选择图片"))
        self.label_2.setText(_translate("Dialo", "请选择头像"))
        self.scanPic.setText(_translate("Dialo", "浏览"))

